<?php

declare(strict_types=1);

// GET /api/country-calling-codes — dial codes for signup (no auth).

$rows = [
    ['dial' => '1', 'name' => 'United States / Canada'],
    ['dial' => '7', 'name' => 'Russia / Kazakhstan'],
    ['dial' => '20', 'name' => 'Egypt'],
    ['dial' => '27', 'name' => 'South Africa'],
    ['dial' => '30', 'name' => 'Greece'],
    ['dial' => '31', 'name' => 'Netherlands'],
    ['dial' => '32', 'name' => 'Belgium'],
    ['dial' => '33', 'name' => 'France'],
    ['dial' => '34', 'name' => 'Spain'],
    ['dial' => '36', 'name' => 'Hungary'],
    ['dial' => '39', 'name' => 'Italy'],
    ['dial' => '40', 'name' => 'Romania'],
    ['dial' => '41', 'name' => 'Switzerland'],
    ['dial' => '43', 'name' => 'Austria'],
    ['dial' => '44', 'name' => 'United Kingdom'],
    ['dial' => '45', 'name' => 'Denmark'],
    ['dial' => '46', 'name' => 'Sweden'],
    ['dial' => '47', 'name' => 'Norway'],
    ['dial' => '48', 'name' => 'Poland'],
    ['dial' => '49', 'name' => 'Germany'],
    ['dial' => '51', 'name' => 'Peru'],
    ['dial' => '52', 'name' => 'Mexico'],
    ['dial' => '53', 'name' => 'Cuba'],
    ['dial' => '54', 'name' => 'Argentina'],
    ['dial' => '55', 'name' => 'Brazil'],
    ['dial' => '56', 'name' => 'Chile'],
    ['dial' => '57', 'name' => 'Colombia'],
    ['dial' => '58', 'name' => 'Venezuela'],
    ['dial' => '60', 'name' => 'Malaysia'],
    ['dial' => '61', 'name' => 'Australia'],
    ['dial' => '62', 'name' => 'Indonesia'],
    ['dial' => '63', 'name' => 'Philippines'],
    ['dial' => '64', 'name' => 'New Zealand'],
    ['dial' => '65', 'name' => 'Singapore'],
    ['dial' => '66', 'name' => 'Thailand'],
    ['dial' => '81', 'name' => 'Japan'],
    ['dial' => '82', 'name' => 'South Korea'],
    ['dial' => '84', 'name' => 'Vietnam'],
    ['dial' => '86', 'name' => 'China'],
    ['dial' => '90', 'name' => 'Turkey'],
    ['dial' => '91', 'name' => 'India'],
    ['dial' => '92', 'name' => 'Pakistan'],
    ['dial' => '93', 'name' => 'Afghanistan'],
    ['dial' => '94', 'name' => 'Sri Lanka'],
    ['dial' => '95', 'name' => 'Myanmar'],
    ['dial' => '98', 'name' => 'Iran'],
    ['dial' => '212', 'name' => 'Morocco'],
    ['dial' => '213', 'name' => 'Algeria'],
    ['dial' => '216', 'name' => 'Tunisia'],
    ['dial' => '218', 'name' => 'Libya'],
    ['dial' => '220', 'name' => 'Gambia'],
    ['dial' => '221', 'name' => 'Senegal'],
    ['dial' => '222', 'name' => 'Mauritania'],
    ['dial' => '223', 'name' => 'Mali'],
    ['dial' => '224', 'name' => 'Guinea'],
    ['dial' => '225', 'name' => "Côte d'Ivoire"],
    ['dial' => '226', 'name' => 'Burkina Faso'],
    ['dial' => '227', 'name' => 'Niger'],
    ['dial' => '228', 'name' => 'Togo'],
    ['dial' => '229', 'name' => 'Benin'],
    ['dial' => '230', 'name' => 'Mauritius'],
    ['dial' => '231', 'name' => 'Liberia'],
    ['dial' => '232', 'name' => 'Sierra Leone'],
    ['dial' => '233', 'name' => 'Ghana'],
    ['dial' => '234', 'name' => 'Nigeria'],
    ['dial' => '235', 'name' => 'Chad'],
    ['dial' => '236', 'name' => 'Central African Republic'],
    ['dial' => '237', 'name' => 'Cameroon'],
    ['dial' => '238', 'name' => 'Cape Verde'],
    ['dial' => '239', 'name' => 'São Tomé and Príncipe'],
    ['dial' => '240', 'name' => 'Equatorial Guinea'],
    ['dial' => '241', 'name' => 'Gabon'],
    ['dial' => '242', 'name' => 'Republic of the Congo'],
    ['dial' => '243', 'name' => 'DR Congo'],
    ['dial' => '244', 'name' => 'Angola'],
    ['dial' => '245', 'name' => 'Guinea-Bissau'],
    ['dial' => '246', 'name' => 'British Indian Ocean Territory'],
    ['dial' => '248', 'name' => 'Seychelles'],
    ['dial' => '249', 'name' => 'Sudan'],
    ['dial' => '250', 'name' => 'Rwanda'],
    ['dial' => '251', 'name' => 'Ethiopia'],
    ['dial' => '252', 'name' => 'Somalia'],
    ['dial' => '253', 'name' => 'Djibouti'],
    ['dial' => '254', 'name' => 'Kenya'],
    ['dial' => '255', 'name' => 'Tanzania'],
    ['dial' => '256', 'name' => 'Uganda'],
    ['dial' => '257', 'name' => 'Burundi'],
    ['dial' => '258', 'name' => 'Mozambique'],
    ['dial' => '260', 'name' => 'Zambia'],
    ['dial' => '261', 'name' => 'Madagascar'],
    ['dial' => '262', 'name' => 'Réunion / Mayotte'],
    ['dial' => '263', 'name' => 'Zimbabwe'],
    ['dial' => '264', 'name' => 'Namibia'],
    ['dial' => '265', 'name' => 'Malawi'],
    ['dial' => '266', 'name' => 'Lesotho'],
    ['dial' => '267', 'name' => 'Botswana'],
    ['dial' => '268', 'name' => 'Eswatini'],
    ['dial' => '269', 'name' => 'Comoros'],
    ['dial' => '290', 'name' => 'Saint Helena'],
    ['dial' => '291', 'name' => 'Eritrea'],
    ['dial' => '297', 'name' => 'Aruba'],
    ['dial' => '298', 'name' => 'Faroe Islands'],
    ['dial' => '299', 'name' => 'Greenland'],
    ['dial' => '350', 'name' => 'Gibraltar'],
    ['dial' => '351', 'name' => 'Portugal'],
    ['dial' => '352', 'name' => 'Luxembourg'],
    ['dial' => '353', 'name' => 'Ireland'],
    ['dial' => '354', 'name' => 'Iceland'],
    ['dial' => '355', 'name' => 'Albania'],
    ['dial' => '356', 'name' => 'Malta'],
    ['dial' => '357', 'name' => 'Cyprus'],
    ['dial' => '358', 'name' => 'Finland'],
    ['dial' => '359', 'name' => 'Bulgaria'],
    ['dial' => '370', 'name' => 'Lithuania'],
    ['dial' => '371', 'name' => 'Latvia'],
    ['dial' => '372', 'name' => 'Estonia'],
    ['dial' => '373', 'name' => 'Moldova'],
    ['dial' => '374', 'name' => 'Armenia'],
    ['dial' => '375', 'name' => 'Belarus'],
    ['dial' => '376', 'name' => 'Andorra'],
    ['dial' => '377', 'name' => 'Monaco'],
    ['dial' => '378', 'name' => 'San Marino'],
    ['dial' => '380', 'name' => 'Ukraine'],
    ['dial' => '381', 'name' => 'Serbia'],
    ['dial' => '382', 'name' => 'Montenegro'],
    ['dial' => '383', 'name' => 'Kosovo'],
    ['dial' => '385', 'name' => 'Croatia'],
    ['dial' => '386', 'name' => 'Slovenia'],
    ['dial' => '387', 'name' => 'Bosnia and Herzegovina'],
    ['dial' => '389', 'name' => 'North Macedonia'],
    ['dial' => '420', 'name' => 'Czech Republic'],
    ['dial' => '421', 'name' => 'Slovakia'],
    ['dial' => '423', 'name' => 'Liechtenstein'],
    ['dial' => '500', 'name' => 'Falkland Islands'],
    ['dial' => '501', 'name' => 'Belize'],
    ['dial' => '502', 'name' => 'Guatemala'],
    ['dial' => '503', 'name' => 'El Salvador'],
    ['dial' => '504', 'name' => 'Honduras'],
    ['dial' => '505', 'name' => 'Nicaragua'],
    ['dial' => '506', 'name' => 'Costa Rica'],
    ['dial' => '507', 'name' => 'Panama'],
    ['dial' => '508', 'name' => 'Saint Pierre and Miquelon'],
    ['dial' => '509', 'name' => 'Haiti'],
    ['dial' => '590', 'name' => 'Guadeloupe'],
    ['dial' => '591', 'name' => 'Bolivia'],
    ['dial' => '592', 'name' => 'Guyana'],
    ['dial' => '593', 'name' => 'Ecuador'],
    ['dial' => '594', 'name' => 'French Guiana'],
    ['dial' => '595', 'name' => 'Paraguay'],
    ['dial' => '596', 'name' => 'Martinique'],
    ['dial' => '597', 'name' => 'Suriname'],
    ['dial' => '598', 'name' => 'Uruguay'],
    ['dial' => '599', 'name' => 'Caribbean Netherlands'],
    ['dial' => '670', 'name' => 'East Timor'],
    ['dial' => '672', 'name' => 'Antarctica / Norfolk Island'],
    ['dial' => '673', 'name' => 'Brunei'],
    ['dial' => '674', 'name' => 'Nauru'],
    ['dial' => '675', 'name' => 'Papua New Guinea'],
    ['dial' => '676', 'name' => 'Tonga'],
    ['dial' => '677', 'name' => 'Solomon Islands'],
    ['dial' => '678', 'name' => 'Vanuatu'],
    ['dial' => '679', 'name' => 'Fiji'],
    ['dial' => '680', 'name' => 'Palau'],
    ['dial' => '681', 'name' => 'Wallis and Futuna'],
    ['dial' => '682', 'name' => 'Cook Islands'],
    ['dial' => '683', 'name' => 'Niue'],
    ['dial' => '685', 'name' => 'Samoa'],
    ['dial' => '686', 'name' => 'Kiribati'],
    ['dial' => '687', 'name' => 'New Caledonia'],
    ['dial' => '688', 'name' => 'Tuvalu'],
    ['dial' => '689', 'name' => 'French Polynesia'],
    ['dial' => '690', 'name' => 'Tokelau'],
    ['dial' => '691', 'name' => 'Micronesia'],
    ['dial' => '692', 'name' => 'Marshall Islands'],
    ['dial' => '850', 'name' => 'North Korea'],
    ['dial' => '852', 'name' => 'Hong Kong'],
    ['dial' => '853', 'name' => 'Macau'],
    ['dial' => '855', 'name' => 'Cambodia'],
    ['dial' => '856', 'name' => 'Laos'],
    ['dial' => '880', 'name' => 'Bangladesh'],
    ['dial' => '886', 'name' => 'Taiwan'],
    ['dial' => '960', 'name' => 'Maldives'],
    ['dial' => '961', 'name' => 'Lebanon'],
    ['dial' => '962', 'name' => 'Jordan'],
    ['dial' => '963', 'name' => 'Syria'],
    ['dial' => '964', 'name' => 'Iraq'],
    ['dial' => '965', 'name' => 'Kuwait'],
    ['dial' => '966', 'name' => 'Saudi Arabia'],
    ['dial' => '967', 'name' => 'Yemen'],
    ['dial' => '968', 'name' => 'Oman'],
    ['dial' => '970', 'name' => 'Palestine'],
    ['dial' => '971', 'name' => 'United Arab Emirates'],
    ['dial' => '972', 'name' => 'Israel'],
    ['dial' => '973', 'name' => 'Bahrain'],
    ['dial' => '974', 'name' => 'Qatar'],
    ['dial' => '975', 'name' => 'Bhutan'],
    ['dial' => '976', 'name' => 'Mongolia'],
    ['dial' => '977', 'name' => 'Nepal'],
    ['dial' => '992', 'name' => 'Tajikistan'],
    ['dial' => '993', 'name' => 'Turkmenistan'],
    ['dial' => '994', 'name' => 'Azerbaijan'],
    ['dial' => '995', 'name' => 'Georgia'],
    ['dial' => '996', 'name' => 'Kyrgyzstan'],
    ['dial' => '998', 'name' => 'Uzbekistan'],
];

usort($rows, static function (array $a, array $b): int {
    return strcmp((string) $a['name'], (string) $b['name']);
});

Http::json(['ok' => true, 'data' => $rows]);
